### ISSUE TITLE
Border radius on c-data Bar

### ISSUE THREAD

**Issue by yaziz** [SalesforceLabs/LightningWebChartJS#28]
Hello,

Is it possible to have border radius option for Data for Bar charts ?
Thank you.

Best Regards.

**Comment by victorgz** [comment]
Hello @yaziz ,

I've checked and unfortunatley Chart.js doesn't expose any option to have border radius for bar charts out of the box. It seems that you need to use an external Chart.js Plugin or to modify the appearence by yourself using the Chartjs API ([more info here](https://www.chartjs.org/docs/latest/developers/)).

Due to some platform limitations, we're don't have those two options available on the LWCC solution. However, it is our main priority for the next big release ! Stay tunned 😉

**Comment by yaziz** [comment]
It is now possible in the new version of chart JS. Could you update your version to give the possibility to apply border radius into dataset element ?
