### ISSUE TITLE
When using the component in a record page, datasets are not displayed as expected

### ISSUE THREAD

**Issue by sanderheuver66** [SalesforceLabs/LightningWebChartJS#36]
## _Who_ is the bug affecting?

Everyone using the component in a record page, created with the Lightning app builder.

## _What_ is affected by this bug?

Line graphs, for multiple datasets.

## _When_ does this occur?

Always.

## _Where_ on the platform does it happen?

In a Lightning record page, after adding the component using the Lightning app builder and specifying Dataset Labels and Datasets and nothing else.

## _How_ do we replicate the issue?

Dataset Labels:
["Buying customers","Returned customers","Lost customers"]
Dataset:
[{"labels":"January", "detail":[1, 2, 3, 4, 5, 6, 7]},{"labels":"February", "detail":[7, 49, 46, 13, 25, 30, 22]},{"labels":"March", "detail":[3, 9, 6, 1, 5, 10, 2]},{"labels":"April", "detail":[13, 29, 36]},{"labels":"May", "detail":[43, 29, 16]},{"labels":"June", "detail":[33, 49, 26]},{"labels":"July", "detail":[13, 29, 36]}]
Result: screenshot "Result with 6 January values"
![Result with 6 January values](https://user-images.githubusercontent.com/44359732/107485748-7bb13c00-6b84-11eb-8d01-1f53b46c3228.png)

Dataset Labels:
["Buying customers","Returned customers","Lost customers"]
Dataset:
[{"labels":"January", "detail":[1, 2, 3]},{"labels":"February", "detail":[7, 49, 46]},{"labels":"March", "detail":[3, 9, 6]},{"labels":"April", "detail":[13, 29, 36]},{"labels":"May", "detail":[43, 29, 16]},{"labels":"June", "detail":[33, 49, 26]},{"labels":"July", "detail":[13, 29, 36]}]
Result: screenshot "Result with 3 January values"
![Result with 3 January values](https://user-images.githubusercontent.com/44359732/107485746-7b18a580-6b84-11eb-9780-744d263cbec0.png)

## Expected behavior (i.e. solution)

Only three lines should be displayed. The values for "January" should not be spread from January - July.

**Comment by victorgz** [comment]
Hi @sanderheuver66 !

We know that the way of working with charts, axis, datasets... sometimes can lead to some confusions, so first of all, let me give you a quick explanation:

- The dataset labels array represents the different sets of data that you will have in your chart
- The dataset array contains objects with your data configuration. In the case of the line chart (cartesian), for each object you define a "labels" value (string, will be placed in the x-Axis of your chart, in the same position as the object is in the array), and a property "detail", that will consist in an array with as many values as labels you have in the dataset.

Now, trying to answer your questions:

### 1. Only three lines should be displayed
The problem comes from the way the data is organized. You can change your dataset array to:
`[ { "labels": "January", "detail": [ 1, 7, 2, 13, 43, 33, 13 ] }, { "labels": "February", "detail": [ 2, 49, 9, 29, 29, 49, 29 ] }, { "labels": "March", "detail": [ 3, 46, 6, 36, 16, 26, 36 ] }, { "labels": "April" }, { "labels": "May" }, { "labels": "June" }, { "labels": "July" } ]`
![image (6)](https://user-images.githubusercontent.com/6944989/108066062-23d07480-705f-11eb-9e13-d30113c622fc.png)
For each "detail" array, the first position will display the value of January, second position February... and therefore, the data for the first dataset object ([ 1, 7, 2, 13, 43, 33, 13 ]) will match with the first dataset label.

**NOTE**: By testing this scenario, we've found a bug that displays undefined dataset labels. We need to fix this.

### 2. The values for "January" should not be spread from January - July.


As you're using static data, you have values from January to July because you have specified labels and details for all those months. If you just want to display less values in the axis, you will just need to modify your dataset to adapt it to this structure:
`[ { "labels": "January", "detail": [ 1, 7, 2 ] }, { "labels": "February", "detail": [ 2, 49, 9 ] }, { "labels": "March", "detail": [ 3, 46, 6] }]`
![image (7)](https://user-images.githubusercontent.com/6944989/108066124-38147180-705f-11eb-9df0-906ec731a62a.png)

Please note that the chart builder version won't remove automatically the axis ticks without data (this is a  specific use case, some people might not want to have it removed). In case you need this dynamic condition, you need to build it yourself using the API of the library.

### Conclusions
We know that this way of structuring the data can seem complicated for some scenarios, but when we built the library we decided to keep do it this way to standardize and to keep the maximum possible options for the App Builder solution: SOQL queries, a chart data provider or static data (as in your case, used for prototyping purposes). As we cannot offer here all the possible combinations, for those people who need more we provide the [LWCC API](https://salesforcelabs.github.io/LightningWebChartJS/docs/api.html) to customize more complex charts. You can also check out the [sample gallery](https://salesforcelabs.github.io/LightningWebChartJS/docs/general/samples.html) to see how to compose them.

We're already thinking of ways to improve this, but for now a change on the way to structure the data would be a big breaking change that impacts thousands of users which are already using the library. 

I hope that this answers your questions, and meanwhile we're going to work on the correction of the undefined dataset labels. We will try to push a new version as soon as possible and will close this issue once it is ready. Stay tuned ! 😃
