### ISSUE TITLE
Alignment legend

### ISSUE THREAD

**Issue by yaziz** [SalesforceLabs/LightningWebChartJS#43]
## _What_ is affected by this bug?

Alignment legend for bar charts

## _How_ do we replicate the issue?

I created a bar chart with end align attribute in legend but the legend is center :

`<c-chart type="bar" responsive="true">
<c-dataset labels='["Item 1","Item 2","Item 3","Item 4", "Item 5","Item 6","Item 7"]'>
<c-data label="Neutral" detail="[40, 47, 44, 38, 27, 31, 25]" backgroundcolor='rgba(50, 150, 237, 1)' stack="1"></c-data>
<c-data label="Warning" detail="[10, 12, 7, 5, 4, 6, 8]" backgroundcolor='rgba(119, 185, 242, 1)' stack="1"></c-data>
<c-data label="Error" detail="[17, 11, 22, 18, 12, 7, 5]" backgroundcolor='rgba(157, 83, 242, 1)' stack="1"></c-data>
</c-dataset>
<c-cartesian-axis axis="x" stacked="true" >
</c-cartesian-axis>
<c-cartesian-axis axis="y" stacked="true"></c-cartesian-axis>
<c-legend align="end"></c-legend>
</c-chart>`

## Expected behavior (i.e. solution)

I expected that the legend is right alignment

**Comment by victorgz** [comment]
Hi @yaziz , thanks for contacting us!

We will have a look at it and let you know soon 😃

**Comment by victorgz** [comment]
Hi @yaziz ,
Bad news... in fact the attribute align on the legend component is not available.
We're using the [version 2.7.3 of Chart.js](https://www.chartjs.org/docs/2.7.3/configuration/legend.html) which didn't have the align attribute, but it seems that we made a mistake and took as reference the [version 2.9.4](https://www.chartjs.org/docs/2.9.4/configuration/legend.html) in which this property was included later.

We use the version 2.7.3 because when the project was built, there were some issues with the CSS injection of 2.9.4 and the Lightning Locker Service.

We're not planning to migrate the current version to 2.9.4, but we're already working on a new release which is using Chart.js 3 😃
In this last version Chart.js still exposes the [align attribute for the legends](https://www.chartjs.org/docs/latest/configuration/legend.html), so we will do it as well.

Stay tunned for the new release comming up soon ! 🚀
