### ISSUE TITLE
Add custom text in legend

### ISSUE THREAD

**Issue by andrewdourado** [SalesforceLabs/LightningWebChartJS#44]
Hello again! 

Is it possible to add text on the next of the legend?

<img width="823" alt="Screen Shot 2021-04-09 at 17 59 17" src="https://user-images.githubusercontent.com/15659599/114240163-793d4980-995d-11eb-9a70-a66ed3c3f909.png">

I tried to use **title** component but it doesn't have the **align** attribute like [ChartJS](https://www.chartjs.org/docs/latest/configuration/title.html#title-configuration)

**Comment by victorgz** [comment]
Hi @andrewdourado , 

It seems that you compared with the wrong version of Chart.js. We're currently using the v2.7.3 in this project instead of the 3.1.0 that you sent in the link. At that moment, the align attribute was not existing - [Chart.js v2.7.3 Documentation](https://www.chartjs.org/docs/2.7.3/configuration/title.html) - so that's why we don't expose it in this library.

Good news is that we're working on a new release to support Chart.js v3, so stay tunned !
