### ISSUE TITLE
Chart undefined in Digital Experience Site with Locker enabled

### ISSUE THREAD

**Issue by amboton1** [SalesforceLabs/LightningWebChartJS#53]
## _What_ is affected by this bug?

Data Visualization - cannot display chart

## _When_ does this occur?

When compoent gets loaded.

We have this enabled in digital experience builder:

![image](https://user-images.githubusercontent.com/19265409/116681954-e9b01700-a9ad-11eb-861b-fde58acf0ed3.png)

We have scripts for chart.js implemented inside staticresources.

Chart only works when locker is disabled.

**Locker is enabled by default so this our issue might have important impact**

**Comment by amboton1** [comment]
Hi @victorgz , thank you for your quick response.

I cloned the project and then i just pushed the code to my scratch org for the test. Then after that i used Chart Builder (drag and drop) on Digital Experience Site Builder and set data source demo. The message was window.Chart not defined.

**Comment by amboton1** [comment]
I misspelled, its this error that i am getting after drag and dropping Chart Builder Component:

![image](https://user-images.githubusercontent.com/19265409/116847661-43515500-abeb-11eb-9f01-ecfb0e200705.png)

**Comment by amboton1** [comment]
Hi @victorgz , we used "Build Your Own (LWR)" template where issue exist.

Now  i've tried with a Partner Central Community and it works, without changing CSP(Locker).

So i would say the issue is in Build Your Own template.

**Comment by victorgz** [comment]
@amboton1 exactly, I've checked and the issues comes from the Build Your Own (LWR) template.
This new template has some limitations, and one of them it is exactly about what you're mentioning above ([link here](https://developer.salesforce.com/docs/atlas.en-us.exp_cloud_lwr.meta/exp_cloud_lwr/template_limitations.htm)):

> **Lightning Locker Limitations**
> LWR sites use an upgraded version of the Lightning Locker library, which currently includes some limitations.
> Scripts loaded through lightning/platformResourceLoader run in system mode outside of a Lightning Locker sandbox. As a result, the component loading the script doesn’t have access to the same global variable scope as the script itself, preventing it from accessing any global variable set by the script.

The documentation proposes as a solution to implement a custom static resource loader, instead of using the standard Salesforce one. We're going to discuss this internally and see whether it is something that we could add to the current version or not.
In fact, we're already working on a new version of the project using ChartJS 3 which is available on an ES Module, so we won't need anymore the static resource (and therefore we won't have the problem with the BYO LWR template).

Meanwhile, I see two workarounds:
- You can just relax the Lightning Locker restriction in your current community
- Otherwise you can try to implement yourself the custom resourceLoader in the cloned repo, and keep the Lightning Locker enabled. And if you choose this option, we would love to hear any feedback from you ! 😄

**Comment by amboton1** [comment]
I am closing this issue for now.
