### ISSUE TITLE
Cannot use avg() aggregate function - distorted donut pie

### ISSUE THREAD

**Issue by JeroenSfdc** [SalesforceLabs/LightningWebChartJS#80]
## _Who_ is the bug affecting?
When using avg() aggregates

## _What_ is affected by this bug?
Visualization

## _When_ does this occur?
Always

## _Where_ on the platform does it happen?
On LWCC

## _How_ do we replicate the issue?
Ex. SOQL

`SELECT AVG(Speeltijd__c) label, Speler__r.Name value FROM Beoordeling__c WHERE Wedstrijd__r.Datum__c = LAST_N_DAYS:180  AND Aanwezigheid__c  = 'Aanwezig' WITH SECURITY_ENFORCED GROUP BY Speler__r.Name LIMIT 10`

![image](https://user-images.githubusercontent.com/27854769/134773687-89661dc7-4c98-48ab-ad6a-bee0440abdd4.png)

![image](https://user-images.githubusercontent.com/27854769/134773659-2925345f-2164-416d-b61e-2ebcaa9b2412.png)

## Expected behavior (i.e. solution)
Ability to create donut chart based on avg() aggregates

**Comment by victorgz** [comment]
Hi @JeroenSfdc and sorry for the late reply ! We've been disconnected during some time, but good news is that we're back !

I've done some tests from my side and the AVG() function seems to work. I think that your problem is in the SOQL query: it seems that you're trying to use the aggregated values as the label, and the chart values as the segments in the doughtnut chart. I don't think that should work, because the library doesn't know how to draw doughnut segments from string values.

> SELECT **AVG(Speeltijd__c) label, Speler__r.Name value** FROM Beoordeling__c WHERE Wedstrijd__r.Datum__c = LAST_N_DAYS:180 AND Aanwezigheid__c = 'Aanwezig' WITH SECURITY_ENFORCED GROUP BY Speler__r.Name LIMIT 10

should be written as:

> SELECT **AVG(Speeltijd__c) value, Speler__r.Name label** FROM Beoordeling__c WHERE Wedstrijd__r.Datum__c = LAST_N_DAYS:180 AND Aanwezigheid__c = 'Aanwezig' WITH SECURITY_ENFORCED GROUP BY Speler__r.Name LIMIT 10

Let me know if that helps, and thanks for using the library !
