### ISSUE TITLE
tickMin / tickMax

### ISSUE THREAD

**Issue by acann22** [SalesforceLabs/LightningWebChartJS#82]
Absolutely loving this package but I cannot for the life of me get the tickmin / tickmax working for the radar chart. c-radial-linear-axis tickmax=10000></c-radial-linear-axis> has no impact on the radar chart.

**Comment by victorgz** [comment]
Hi @acann22, thanks for reaching out and loving the library !

Effectively there was a problem with some numeric attributes, as the LWC core library parses them as strings instead of numbers when they are defined in the HTML template. I have just created a PR that normally should fix it.

Stay tunned for the next release ! 🚀
